'use strict';
// Independent H audit: raw fixtures, first resolution, immutable input checks.
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),ctx={window:{},console};vm.createContext(ctx);
for(const p of ['legacy/js/core/rng.js','legacy/js/data/content.js','legacy/js/engine/resolver.js','legacy/js/core/game.js','legacy/js/core/validation.js','legacy/js/core/save.js'])vm.runInContext(fs.readFileSync(path.join(root,p),'utf8'),ctx,{filename:p});
const G=ctx.window.Game,cases=[],eq=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));
function test(name,fn){try{fn();cases.push({name:'independent-H/'+name,ok:true});}catch(e){cases.push({name:'independent-H/'+name,ok:false,error:e.message});}}
function raw(types){const s=G.newRun('H-INDEPENDENT-BOUNDARIES');s.symbols=[];const board=Array(20).fill(null);types.forEach(([t,p,extra])=>{const x=G.instance(s,t);Object.assign(x,extra||{});s.symbols.push(x);board[p]=x.uid;});return {s,board};}
function run(f){const before=JSON.stringify(f.s),s=G.clone(f.s),r=G.resolve(s,f.board);eq(JSON.stringify(f.s),before);eq(r.ledger.map(x=>x.pos),r.ledger.map(x=>x.pos).slice().sort((a,b)=>a-b));return {s,r};}
const money=r=>r.ledger.map(x=>x.amount);
function cmd(s,c){const b=JSON.stringify(s),r=G.command(s,Object.assign({revision:s.revision},c));eq(JSON.stringify(s),b);assert(r.ok,r.error);return r.state;}
function reject(s,c){const b=JSON.stringify(s),r=G.command(s,Object.assign({revision:s.revision},c));eq([r.ok,r.state===s,JSON.stringify(s)],[false,true,b]);}
function accept(f){f.s=cmd(f.s,{type:'configureStage',accepted:true});return f;}
test('arrears-two-negative-with-permanent',()=>{const f=raw([['arrears_slip',0],['arrears_slip',19,{permanent:2}]]),{r}=run(f);eq([money(r),r.reward,r.total],[[-1,1],0,0]);});
test('junk-never-offered-across-128-draws',()=>{const s=G.newRun('H-DRAWS');for(let i=0;i<128;i++){const c=G.choices(s);eq(c.length,3);assert(c.every(id=>!G.symbols[id].tags.includes('junk')));}});
for(const [cash,payment,v] of [[4,9,5],[5,9,1],[9,18,1],[8,18,5],[1,0,1]])test('lean-ratio-'+cash+'-'+payment,()=>{const f=raw([['lean_receipt',8,{permanent:2}]]);Object.assign(f.s,{cash,payment});const {r,s}=run(f);eq([money(r),r.reward,r.total,s.rngState,s.nextId],[[v+2],0,v+2,f.s.rngState,f.s.nextId]);});
for(const [gap,v] of [[0,2],[1,8],[15,8],[16,2],[-1,2]])test('quota-gap-'+gap,()=>{const f=raw([['quota_margin',8,{permanent:3}]]);f.s.cash=30-gap;const {r}=run(f);eq([money(r),r.reward,r.total],[[v+3],0,v+3]);});
test('desk-picks-one-preserves-uid-permanent-clears-counter-reservation',()=>{const f=raw([['compliance_desk',6],['arrears_slip',7,{permanent:6,counters:{age:9,pressure:2}}],['arrears_slip',11]]);f.s.reservations=[{uid:f.board[7],pos:7,source:f.board[6]}];const {r,s}=run(f);eq([money(r),r.total],[[1,9,-1],9]);eq(s.symbols[1],{uid:f.board[7],type:'cleared_stub',permanent:6,counters:{}});eq(s.reservations,[]);eq(r.log.filter(x=>x.type==='add'),[]);});
test('desk-distant-negative-untouched',()=>{const f=raw([['compliance_desk',4],['arrears_slip',15,{permanent:2}]]),{r,s}=run(f);eq([money(r),r.total,s.symbols],[[1,1],2,f.s.symbols]);});
test('two-desks-compete-by-position',()=>{const f=raw([['compliance_desk',5],['arrears_slip',6],['compliance_desk',7]]),{r}=run(f);eq([money(r),r.total],[[1,3,1],5]);eq(r.log.filter(x=>x.type==='transform').map(x=>[x.source,x.target]),[[f.board[5],f.board[6]]]);});
test('stub-direct-appear-plus-permanent',()=>{const {r}=run(raw([['cleared_stub',10,{permanent:4}]]));eq([money(r),r.reward,r.total],[[8],0,8]);eq(r.log.filter(x=>x.type==='add').map(x=>x.amount),[1]);});
test('copy-transformed-junk-has-no-initial-whitelisted-add',()=>{const f=raw([['offset_reader',5],['arrears_slip',6],['compliance_desk',7]]),{r}=run(f);eq([money(r),r.total,r.log.filter(x=>x.type==='copy')],[[1,3,1],5,[]]);});
test('copy-initial-stub-flat-one',()=>{const f=raw([['offset_reader',10],['cleared_stub',11,{permanent:2}]]),{r}=run(f);eq([money(r),r.total],[[2,6],8]);eq(r.log.filter(x=>x.type==='copy').map(x=>[x.target,x.amount]),[[f.board[11],1]]);});
for(const [p,want,inc] of [[28,29,1],[30,30,0]])test('clerk-cap-'+p,()=>{const f=raw([['cancellation_clerk',10,{permanent:p}],['arrears_slip',11,{permanent:17}]]),{r,s}=run(f);eq([money(r),r.reward,r.total],[[1+want,0],5,6+want]);eq(s.symbols.map(x=>x.permanent),[want]);eq(r.log.filter(x=>x.type==='grow').map(x=>x.actualIncrease),[inc]);});
test('clerks-one-target-one-growth-and-tombstone',()=>{const f=raw([['cancellation_clerk',10],['arrears_slip',11],['cancellation_clerk',12]]),{r,s}=run(f);eq([money(r),r.reward,r.total,s.symbols.map(x=>x.permanent)],[[2,0,1],5,8,[1,0]]);eq(r.ledger[1].alive,false);});
test('clerk-no-junk-no-grow',()=>{const {r,s}=run(raw([['cancellation_clerk',18],['advance_stamp',19]]));eq([money(r),r.total,r.reward,s.symbols[0].permanent],[[1,2],3,0,0]);});
test('stamp-default-neutral-exact',()=>{const f=raw([['advance_stamp',9,{permanent:3}]]),{r,s}=run(f);eq([money(r),r.reward,r.total,s.payment,s.nextId,s.stageState],[[5],0,5,30,f.s.nextId,{claims:[],paymentModifiers:[]}]);});
test('ready-setting-revision-and-stale-byte-atomic',()=>{const s=G.newRun('H-CONFIG'),n=cmd(s,{type:'configureStage',accepted:true});eq([n.revision,n.settings.advanceAccepted,s.settings.advanceAccepted],[1,true,false]);reject(n,{type:'configureStage',accepted:false,revision:0});for(const accepted of [1,'false',null])reject(n,{type:'configureStage',accepted});const p=cmd(n,{type:'spin'});reject(p,{type:'configureStage',accepted:false});});
test('stamp-cash-snapshot-not-raised-payment',()=>{const f=accept(raw([['advance_stamp',5],['lean_receipt',6],['quota_margin',7]]));f.s.cash=15;const {r,s}=run(f);eq([money(r),r.reward,r.total,s.payment],[[2,1,8],18,29,38]);});
test('stamp-exact-contract-once-and-uid',()=>{const f=accept(raw([['advance_stamp',9,{permanent:4}]])),{r,s}=run(f),key='advance_stamp/advance-once';eq([money(r),r.reward,r.total,s.payment,s.nextId,s.rngState],[[6],18,24,38,f.s.nextId+1,f.s.rngState]);eq(s.stageState,{claims:[{source:f.board[9],effectKey:key}],paymentModifiers:[{source:f.board[9],effectKey:key,amount:8}]});eq(r.log.find(x=>x.type==='stageAdvance').stageContract,{reward:18,paymentIncrease:8,paymentBefore:30,paymentAfter:38,createdUid:'u'+f.s.nextId});const again=run({s,board:f.board});eq([again.r.total,again.r.reward,again.s.payment,again.s.nextId],[6,0,38,s.nextId]);});
for(const count of [199,200])test('stamp-pool-boundary-'+count,()=>{const f=accept(raw([['advance_stamp',9]]));while(f.s.symbols.length<count)f.s.symbols.push(G.instance(f.s,'wick_bed'));const {r,s}=run(f);eq([r.reward,r.total,s.payment,s.symbols.length,s.nextId],[18,20,38,200,f.s.nextId+(count===199?1:0)]);eq(r.log.find(x=>x.type==='stageAdvance').stageContract.createdUid,count===199?'u'+f.s.nextId:null);eq(r.log.filter(x=>x.type==='limitSkipped').map(x=>x.reason),count===200?['pool-full']:[]);});
test('stamp-four-instances-obligations-survive-spawn-cap',()=>{const f=accept(raw([['advance_stamp',5],['advance_stamp',6],['advance_stamp',7],['advance_stamp',8]])),{r,s}=run(f);eq([money(r),r.reward,r.total,s.payment,s.nextId,s.stageState.claims.length],[[2,2,2,2],72,80,62,f.s.nextId+2,4]);eq(r.log.filter(x=>x.type==='limitSkipped').map(x=>x.reason),['definition-spawns','definition-spawns']);});
test('offboard-stamp-no-claim',()=>{const f=accept(raw([['wick_bed',9]]));f.s.symbols.push(G.instance(f.s,'advance_stamp'));const {r,s}=run(f);eq([money(r),r.reward,r.total,s.payment,s.stageState.claims],[[2],0,2,30,[]]);});
test('pending-reload-remove-source-choose-obligation-retained',()=>{const f=accept(raw([['advance_stamp',9]]));let s=cmd(f.s,{type:'spin',board:f.board});s=G.decode(G.encode(s));eq([s.cash,s.pendingSettlement,s.payment],[0,20,38]);s=cmd(s,{type:'remove',uid:f.board[9]});eq([s.pendingSettlement,s.payment,s.stageState.claims[0].source],[20,38,f.board[9]]);s=cmd(s,{type:'choose',index:null});eq([s.cash,s.pendingSettlement,s.payment],[20,null,38]);reject(s,{type:'choose',index:null});});
test('stage-reset-clears-claims-preserves-acceptance',()=>{const f=accept(raw([['advance_stamp',9]]));Object.assign(f.s,{cash:60,spinsRemaining:1});let s=cmd(f.s,{type:'spin',board:f.board});s=cmd(s,{type:'choose',index:null});eq([s.cash,s.phase],[42,'ITEM_CHOICE']);s=cmd(s,{type:'reward',index:0});eq([s.stage,s.payment,s.settings.advanceAccepted,s.stageState],[1,59,true,{claims:[],paymentModifiers:[]}]);});
for(const [cash,phase,end] of [[17,'LOST',37],[18,'WON',0],[19,'WON',1]])test('final-payment-'+cash,()=>{const f=accept(raw([['advance_stamp',9]]));Object.assign(f.s,{cash,stage:9,spinsRemaining:1});let s=cmd(f.s,{type:'spin',board:f.board});eq([s.cash,s.pendingSettlement,s.payment],[cash,20,38]);s=cmd(s,{type:'choose',index:null});eq([s.phase,s.cash],[phase,end]);});
test('beacon-whole-pool-junk-blocks',()=>{const f=raw([['settlement_beacon',5],['cleared_stub',6],['advance_stamp',7]]);f.s.symbols.push(G.instance(f.s,'arrears_slip'));const {r}=run(f);eq([money(r),r.total,r.log.filter(x=>x.type==='multiply')],[[2,4,2],8,[]]);});
test('beacon-distinct-types-not-instance-count',()=>{const {r}=run(raw([['settlement_beacon',5],['cleared_stub',6],['cleared_stub',7],['cleared_stub',8]]));eq([money(r),r.total],[[2,4,4,4],14]);});
test('beacon-consumed-junk-tombstone-is-excluded',()=>{const f=raw([['settlement_beacon',5],['cancellation_clerk',6],['arrears_slip',7],['advance_stamp',19]]),{r}=run(f);eq([money(r),r.reward,r.total],[[4,4,0,4],5,17]);eq(r.ledger.map(x=>x.alive),[true,true,false,true]);});
test('beacon-three-sources-cap-at-fourfold',()=>{const {r}=run(raw([['settlement_beacon',5],['settlement_beacon',6],['settlement_beacon',7],['lean_receipt',8],['advance_stamp',19]]));eq([money(r),r.total],[[8,8,8,20,8],52]);eq(r.ledger.map(x=>x.ratio),Array(5).fill(['4','1']));eq(r.log.filter(x=>x.type==='limitSkipped').length,5);});
for(const rules of ['0.2','0.3'])test('migration-pending-'+rules,()=>{const f=raw([['arrears_slip',9]]);let s=cmd(f.s,{type:'spin',board:f.board});delete s.contentVersion;delete s.stageState;delete s.settings.advanceAccepted;s.rules=rules;const before=JSON.stringify(s),n=G.decode(before);eq([n.contentVersion,n.settings.advanceAccepted,n.stageState,n.cash,n.pendingSettlement,n.rngState,n.choices],['H-1',false,{claims:[],paymentModifiers:[]},s.cash,s.pendingSettlement,s.rngState,s.choices]);eq(JSON.stringify(s),before);});
const bad=[['future-content',s=>s.contentVersion='H-9'],['missing-H-stage',s=>delete s.stageState],['unknown-stage',s=>s.stageState.extra=[]],['unsupported-active',s=>s.activeModifiers=[{}]],['numeric-setting',s=>s.settings.advanceAccepted=1],['unknown-claim',s=>s.stageState.claims=[{source:'u1',effectKey:'arrears_slip/x'}]],['uid-upper-bound',s=>s.stageState.claims=[{source:'u'+s.nextId,effectKey:'advance_stamp/advance-once'}]],['missing-modifier',s=>s.stageState.claims=[{source:'u1',effectKey:'advance_stamp/advance-once'}]]];
for(const [name,mutate] of bad)test('schema-'+name,()=>{const s=G.newRun('BAD-H');mutate(s);const b=JSON.stringify(s);assert.throws(()=>G.decode(b));reject(s,{type:'spin'});eq(JSON.stringify(s),b);});
for(const [name,mutate] of [['duplicate-claim',s=>s.stageState.claims.push(G.clone(s.stageState.claims[0]))],['duplicate-modifier',s=>s.stageState.paymentModifiers.push(G.clone(s.stageState.paymentModifiers[0]))],['wrong-amount',s=>s.stageState.paymentModifiers[0].amount=9],['fraction',s=>s.stageState.paymentModifiers[0].amount=8.1],['extra-field',s=>s.stageState.claims[0].extra=true],['payment-under-obligation',s=>s.payment=7]])test('earned-schema-'+name,()=>{const f=accept(raw([['advance_stamp',9]])),{s}=run(f);mutate(s);assert.throws(()=>G.decode(JSON.stringify(s)));reject(s,{type:'spin'});});
test('recursive-stage-rejected-without-mutating-cycle',()=>{const s=G.newRun('CYCLE');s.stageState.paymentModifiers.push(s.stageState);assert.throws(()=>G.validateState(s));eq(s.stageState.paymentModifiers[0]===s.stageState,true);});
test('payment-overflow-spin-byte-atomic',()=>{const f=accept(raw([['advance_stamp',9]]));f.s.payment=1e9;reject(f.s,{type:'spin',board:f.board});});
test('import-single-write-and-fault-atomic',()=>{const a=G.newRun('A'),b=G.newRun('B'),f=accept(raw([['advance_stamp',9]])),s=cmd(f.s,{type:'spin',board:f.board}),key='fog-port.save.v1',back=key+'.backup';for(const fault of [false,true]){const map=new Map([[key,G.encode(a)],[back,G.encode(b)]]),before=JSON.stringify([...map]),writes=[],st={getItem:k=>map.get(k)||null,setItem:(k,v)=>{if(fault)throw Error('quota');writes.push(k);map.set(k,v);}};if(fault){assert.throws(()=>G.commitImport(st,s));eq(JSON.stringify([...map]),before);}else{G.commitImport(st,s);eq(writes,[key]);eq(map.get(back),G.encode(b));eq(G.load(st).state,s);}}});
test('clerk-other-consumer-no-owned-growth',()=>{const f=raw([['sieve_drum',10],['arrears_slip',11],['cancellation_clerk',12]]),{r,s}=run(f);eq([money(r),r.reward,r.total],[[2,2,1],0,5]);eq(s.symbols.find(x=>x.type==='cancellation_clerk').permanent,0);});
test('dead-clerk-and-beacon-cannot-listen',()=>{const old=G.symbols.press.effects;try{G.symbols.press.effects=[{trigger:'ON_ADJACENT',action:'destroy',scope:'self',target:'adj:contract',priority:-10}];for(const type of ['cancellation_clerk','settlement_beacon']){const f=raw([['press',10],[type,11],['cleared_stub',12],['advance_stamp',19]]),{r}=run(f);eq([money(r),r.reward,r.total],[[1,0,4,2],0,7]);eq(r.log.filter(x=>x.source===f.board[11]&&(x.type==='grow'||x.type==='multiply')),[]);}}finally{G.symbols.press.effects=old;}});
test('beacon-with-fractional-other-definition-floors-once',()=>{const old=G.symbols.lean_receipt.tags;try{G.symbols.lean_receipt.tags=old.concat('product');const f=raw([['split_register',0],['settlement_beacon',1],['settlement_beacon',2],['lean_receipt',6],['cleared_stub',19],['advance_stamp',18]]);f.s.cash=30;const {r}=run(f);eq([money(r),r.reward,r.total],[[8,8,8,6,8,16],0,54]);eq(r.ledger.find(x=>x.uid===f.board[6]).ratio,['12','2']);}finally{G.symbols.lean_receipt.tags=old;}});
const freeze=JSON.parse(fs.readFileSync(path.join(root,'tests/route-h-freeze.json'),'utf8')),hashResults=[];
function walk(x){if(!x||typeof x!=='object')return;for(const [k,v]of Object.entries(x)){if(k.includes('/')&&typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)){const p=path.join(root,k);hashResults.push({path:k,ok:fs.existsSync(p)&&crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')===v});}else if(k.includes('/')&&v&&v.frozenSHA256){hashResults.push({path:k,ok:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,k))).digest('hex')===v.frozenSHA256});}else walk(v);}}walk(freeze);
const result={total:cases.length,passed:cases.filter(x=>x.ok).length,failed:cases.filter(x=>!x.ok).length,cases,freezeHashCount:hashResults.length,freezeHashBad:hashResults.filter(x=>!x.ok)};
console.log(JSON.stringify(result,null,2));process.exitCode=result.failed||result.freezeHashBad.length?1:0;

if(process.argv.includes('--browser')){
  const cp=require('child_process'),http=require('http'),os=require('os');
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'route-h-independent-'));
  const expected=JSON.parse(fs.readFileSync(path.join(root,'tests/route-h-suite-manifest.json'),'utf8')).cases;
  const edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
  const results=[];
  function dump(url,profile,name){return new Promise((res,rej)=>{const p=cp.spawn(edge,['--headless','--disable-gpu','--no-first-run','--user-data-dir='+profile,'--dump-dom',url]);let dom='',stderr='';p.stdout.on('data',x=>dom+=x);p.stderr.on('data',x=>stderr+=x);p.on('error',rej);p.on('close',exit=>{const artifact=path.join(directory,name+'.html');fs.writeFileSync(artifact,dom);fs.writeFileSync(path.join(directory,name+'-stderr.txt'),stderr);if(exit!==0)return rej(Error('Edge exit '+exit));res({dom,artifact,profile,exit});});});}
  function inspect(d,name){assert(/data-(result|smoke)="pass"/.test(d.dom),'strict marker '+name);const result={name,artifact:d.artifact,profile:d.profile,exit:d.exit,strictMarker:true};if(name.endsWith('suite')){const m=JSON.parse(/<script id="suite-manifest" type="application\/json">([\s\S]*?)<\/script>/.exec(d.dom)[1]);eq(m.cases,expected);result.total=m.total;result.passed=m.passed;result.exactNameOrderOkError=true;}if(name.endsWith('ui')){const m=/<pre id="smoke-result">([\s\S]*?)<\/pre>/.exec(d.dom),j=JSON.parse(m[1].replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&amp;/g,'&'));const faults=j.evidence.find(x=>x&&x.mechanicsImportFaults).mechanicsImportFaults;eq(faults.map(x=>[x.name,x.ok]),['validation','preview-render','getItem','serialization','capacity','setItem'].map(x=>['mechanics-ui/import-'+x,true]));result.faults=faults;const h=j.evidence.find(x=>x&&x.routeHUI).routeHUI;assert.equal(h.length,3);assert(h.every(x=>x.ok));result.hCases=h;}results.push(result);}
  (async()=>{const fileProfile=path.join(directory,'file-profile');for(const [file,name]of [['index.html','file-suite'],['ui-smoke.html','file-ui'],['storage-smoke.html?write','file-storage-write'],['storage-smoke.html?read','file-storage-read']])inspect(await dump('file:///'+root.replace(/\\/g,'/')+'/tests/'+file,fileProfile,name),name);
  const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(p,(error,data)=>{if(error){res.writeHead(404);return res.end();}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':'text/html; charset=utf-8');res.end(data);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const [file,name]of [['index.html','http-suite'],['ui-smoke.html','http-ui']])inspect(await dump('http://127.0.0.1:'+server.address().port+'/tests/'+file,path.join(directory,name+'-profile'),name),name);}finally{server.close();}
  fs.writeFileSync(path.join(directory,'browser-proof.json'),JSON.stringify({ok:true,results},null,2));console.log('INDEPENDENT_BROWSER '+JSON.stringify({ok:true,directory,results}));})().catch(error=>{console.error(error);process.exitCode=1;});
}
