'use strict';
// Deliberately explicit paper calculations, not a gameplay resolver. Reads GDD BODY
// base/tag rows, never imports GDD1 runtime or oracle-integrity.
const fs=require('node:fs'),path=require('node:path');
const dir=__dirname,gdd=fs.readFileSync(path.join(dir,'../../docs/GAME_DESIGN_V1.md'),'utf8'),original=JSON.parse(fs.readFileSync(path.join(dir,'hand-oracles.json'),'utf8'));
const defs=new Map();for(const line of gdd.split('\n')){const c=line.split('|').map(x=>x.trim());if(c.length===9&&['common','uncommon','rare','epic'].includes(c[3]))defs.set(c[1],{base:Number(c[5]),tags:c[4].split(',')});}
if(defs.size!==64)throw Error('BODY definitions incomplete');
const adjacent=(a,b)=>a!==b&&Math.abs(Math.floor(a/5)-Math.floor(b/5))<=1&&Math.abs(a%5-b%5)<=1;
const papers=[
 {types:{u1:'dew_lantern'},add:{u2:1,u3:4},reward:[],notes:['mist age2+1 reaches3; same UID dew epoch1 age0','root global plant conversion growth1; root1 adjacent echo2, actual1*4','one conversion is below nursery threshold2']},
 {types:{u1:'dew_lantern',u4:'amber_frond'},add:{u1:4,u2:1,u3:4},ratio:{u1:[3,2],u2:[3,2],u4:[3,2],u5:[3,2]},reward:[2],notes:['natural mist2->dew0 and dew1->amber, two plant successes','root29+min(1,30-29)=30; second request actual0 so no growth/echo/item','wrap first living plant u1+4; nursery multiplies all four surviving plants incl itself','individual floors 10,46,5,6,3; reward2 unmultiplied']},
 {types:{u2:'amber_frond'},add:{u2:4,u4:1,u5:4},ratio:{u1:[3,1]},dead:['u2'],reward:[4,3,8],notes:['dew1 matures before valve, root6 grows and adjacent echo7 adds4','wrap amber4+4 ordinary is lost on death; amber independent4 survives','valve0 adjacent amber1, consumes; pressure0+2+index1=3; tower5 consumes3 ->0 below valve threshold6; no self14']},
 {add:{u3:1,u4:4},dead:['u2'],reward:[6,3,2],created:[['u5','copper_burr',0,0,{}]],notes:['tong0 consumes ash1; heat6 grows once and echo7 adjacent adds4','ash death consumes branch creates u5; nextUid6; no self3','apron3/growth2 once; new copper has no ledger/appearance this spin']},
 {add:{u3:1,u4:4},ratio:{u1:[3,2],u3:[3,2],u5:[3,2],u7:[3,2]},dead:['u2','u6'],reward:[6,6,3,2],created:[['u8','copper_burr',0,0,{}]],notes:['ash natural age2->3 remains until step6; tong0 consumes before self-destroy','tong10 consumes spent11; two different scrap successes; heat only first growth1, echo4 once','auditor surviving machines including itself multiply3/2; each tong floor1.5=1','new u8 pool-only nextUid9; no ash self reward']},
 {types:{u6:'dew_lantern'},add:{u2:7,u4:2,u7:1,u8:4},ratio:{u2:[3,1]},reward:[],notes:['split0 locks product copper1; two genuine new tags; cloth6 neighbor copper1 adds5 once','copper1 neighbor machine chord2 adds2; flat2+5+2=9','chord2 sees distinct resonance copper1/dock3, lowest target copper1 x2; split3/2 gives ratio3','dock3 same row other copper/chord two types adds2; root15 adjacent echo16']},
 {types:{u6:'dew_lantern'},add:{u1:8,u3:2,u7:1,u8:4},ratio:{u1:[2,1]},reward:[],notes:['phase0 sees pitch1 resonance, adds resonance not crystal; cloth5 adjacent adds5','chord6 sees phase0/pitch1/dock2, lowest resonance phase0 x2','pitch1 locks lowest neighbor phase0 +3 after preprocessing; phase flat2+5+3=10','dock2 row phase/pitch two other types +2']},
 {types:{u5:'dew_lantern'},add:{u4:3,u6:1,u7:4},ratio:{u1:[3,1]},dead:['u2'],reward:[3,8,12],notes:['valve0 consumes wick1: pressure1->3; index immediate ->4; tower5 deduct3 ->1, marks release','third release stage count2->3 receipt12 once; no self-release14','pause6 neighbor valve0/tower5 pressure tag: base2+copyable1+conditional2=5, no pressure mechanism','mist10->dew triggers root15+1 then echo16+4']},
 {types:{u5:'dew_lantern'},add:{u6:1,u7:4},dead:['u2','u4'],reward:[2,4,18],notes:['reserve0 consumes adjacent amber1: pressure3+2+index1=6','router5 destroys junk6 not consumes; first actual pressure target reserve0 capped6, delta0 no event/index','reserve self18 ->0; amber own independent4; no heat/root growth on destroy']},
 {types:{u1:'dew_lantern',u2:'dew_lantern'},add:{u1:4,u4:2,u5:8},reward:[2],notes:['natural mist0 age2 matures, mist1 age1->2; calendar filters mature0 selects1 ->3 ->dew','fog UIDu2 guard prevents second maturity, remaining2 unchanged; stitcher has no remaining legal target','root global two successes permanent2; echo7 neighbor root6 actual1*4 twice; wrap first only; growth item first only2']},
 {types:{u2:'tide_prism',u3:'dew_lantern'},add:{u2:7,u3:4,u4:1,u5:4,u6:2,u8:6},reward:[7,2],notes:['draw blank17/reserve18/index19 three crystal types =>gauge7 once reserved cleared','mist10 matures =>wrap4, root15+1, echo16+4; coil0 adjacent saline1 converts to tide epoch1','tide own transform+3 then lining+4 =>base4+7=11; saline not plant so no extra root','blank own appearance+2 and crystal index two distinct other types+6; converted tide no new appearance']}
];
const results=original.cases.map((c,i)=>{const p=papers[i],ledger=c.initial.map(([pos,uid,type,permanent])=>{const t=p.types?.[uid]||type,flat=defs.get(t).base+permanent+(p.add?.[uid]||0),[n,d]=p.ratio?.[uid]||[1,1],alive=!(p.dead||[]).includes(uid);return [pos,uid,t,flat,n,d,alive?Math.floor(flat*n/d):0,alive];});
 const pending=ledger.reduce((a,r)=>a+r[6],0)+p.reward.reduce((a,b)=>a+b,0);
 const rewardAmounts=c.rewards.map(x=>x[1]).sort((a,b)=>a-b),actualRewards=p.reward.slice().sort((a,b)=>a-b);
 const same=x=>JSON.stringify(x[0])===JSON.stringify(x[1]);
 const checks={ledger:same([ledger,c.ledger]),reward:same([actualRewards,rewardAmounts]),created:same([p.created||[],c.created]),removed:same([p.dead||[],c.removed]),pending:pending===c.pending};
 const geometry=c.initial.some(x=>x[2]==='echo_plate')?c.initial.filter(x=>['root_ledger','heat_clerk'].includes(x[2])).every(x=>c.initial.some(y=>y[2]==='echo_plate'&&adjacent(x[0],y[0]))):true;
 return {id:c.id,ok:Object.values(checks).every(Boolean)&&geometry,checks,geometry,ledger,independentRewards:p.reward,pending,derivation:p.notes,scope:'Manual semantic recalculation; not gameplay execution'};});
const result={source:'Frozen GDD BODY, explicit independent paper derivation',total:results.length,passed:results.filter(x=>x.ok).length,results};
fs.writeFileSync(path.join(dir,'audit-oracles.json'),JSON.stringify(result,null,2)+'\n');console.log(result.passed+'/'+result.total+' semantic hand recalculations');process.exitCode=results.some(x=>!x.ok)?1:0;
