(function(root){
'use strict';
root.runGdd1F2Tests=function(){
const F=root.GDD1,cases=[],A=(x,m='assert')=>{if(!x)throw Error(m)},J=x=>JSON.stringify(x),eq=(a,b)=>A(J(a)===J(b),J(a)+' != '+J(b));
const test=(name,fn)=>{try{fn();cases.push({name:'f2/'+name,ok:true})}catch(e){cases.push({name:'f2/'+name,ok:false,error:e.message})}};
const fresh=()=>F.sliceNewRun('F2-GOLDEN');
function resolved(entries,items=[],modifiers=[]){const s=F.createFoundationState('F2-HAND');s.pool=entries.map(([type,pos,counters={},perm=0])=>{const x=F.instance(s,type);Object.assign(x.counters,counters);x.permanent=perm;return x});s.spin=s.stageSpin=1;s.spinsRemaining=5;s.itemState.spin=1;s.items=items;s.itemState.stageId=1;
 for(const id of items){s.itemState.quotas[id]={spin:0,stage:0,run:0};s.itemState.used[id]={spin:false,stage:false}}
 s.events.activeModifiers=modifiers;const board=Array(20).fill(null);entries.forEach((e,i)=>board[e[1]]=s.pool[i]);return{s,r:F.sliceResolve(s,board)}}
const amounts=r=>r.ledger.map(x=>x.amount);
test('new-run-exact-12-uids-payments',()=>{const s=fresh();eq(s.pool.map(x=>x.type),['mist_pouch','mist_pouch','wick_bed','wick_bed','ash_felt','ash_felt','copper_burr','copper_burr','saline_ampoule','saline_ampoule','brine_strip','spent_gasket']);eq(s.pool.map(x=>x.uid),Array.from({length:12},(_,i)=>'u'+(i+1)));eq([s.nextUid,s.payment,s.cash,s.removeTokens,s.rerollTokens],[13,46,0,2,2]);eq(F.STREAMS.map(x=>s.rng[x].consumed),[0,0,0,0,0])});
const singles={mist_pouch:1,wick_bed:2,dew_lantern:3,amber_frond:4,fog_stitcher:1,root_ledger:1,warm_pod:1,nursery_gauge:2,ash_felt:1,sorting_tong:1,copper_burr:2,spent_gasket:-1,sieve_drum:2,heat_clerk:1,clinker_router:2,furnace_auditor:2,brine_strip:1,saline_ampoule:2,condense_coil:1,tide_prism:4,deep_still:2,crystal_index:1,pearl_separator:2,reserve_facet:2};
for(const [type,base]of Object.entries(singles))test('symbol/'+type+'/no-target-base',()=>{const {s,r}=resolved([[type,0]]);eq([r.total,r.reward,amounts(r)],[base,0,[base]]);eq(F.STREAMS.map(k=>s.rng[k].consumed),[0,0,0,0,0])});
test('age/mist-natural-growth-immediate-chain',()=>{const {s,r}=resolved([['mist_pouch',0,{age:2}],['root_ledger',1],['nursery_gauge',19]]);eq(amounts(r),[3,2,2]);eq(r.total,7);eq(s.pool[0],{uid:'u1',type:'dew_lantern',permanent:0,epoch:1,counters:{age:0}});eq(r.log.map(x=>[x.action,x.parent,x.source,x.target]),[['age',null,'u1','u1'],['transform',0,'u1','u1'],['grow',1,'u2','u2']])});
test('age/dew-amber-and-brine-saline',()=>{const {s,r}=resolved([['dew_lantern',0,{age:1}],['brine_strip',1,{age:1}]]);eq(s.pool.map(x=>[x.type,x.epoch,x.counters]),[['amber_frond',1,{}],['saline_ampoule',1,{}]]);eq(amounts(r),[4,2])});
test('appearance/fuel-snapshot-survives-consumption',()=>{const {r}=resolved([['warm_pod',0],['wick_bed',1],['reserve_facet',2]]);eq(amounts(r),[4,0,2]);eq([r.reward,r.total],[2,8])});
test('consume/ash-death-listener-generates-next-uid-only',()=>{const {s,r}=resolved([['sorting_tong',0],['ash_felt',1],['heat_clerk',6],['copper_burr',19]]);eq(amounts(r),[1,0,2,2]);eq([r.reward,r.total],[6,11]);eq(s.pool.map(x=>[x.uid,x.type]),[['u1','sorting_tong'],['u3','heat_clerk'],['u4','copper_burr'],['u5','copper_burr']]);eq(s.nextUid,6);eq(r.log.filter(e=>e.action==='spawn').map(e=>e.facts.createdUid),['u5']);A(!r.ledger.some(x=>x.uid==='u5'));eq(r.log.filter(e=>e.action==='grow').map(e=>[e.source,e.amount]),[['u3',1]])});
test('consume/two-consumers-only-success-pays',()=>{const {r}=resolved([['sorting_tong',0],['spent_gasket',1],['sorting_tong',2]]);eq(amounts(r),[1,0,1]);eq(r.reward,6);eq(r.log.filter(e=>e.action==='consume').length,1)});
test('ash/end-third-appearance-self-destroy-reward',()=>{const {s,r}=resolved([['ash_felt',0,{age:2}]]);eq([s.pool.length,r.total,r.reward,amounts(r)],[0,3,3,[0]]);eq(r.log.map(e=>e.action),['age','destroy','reward'])});
test('ash/third-appearance-consumed-no-self-reward',()=>{const {s,r}=resolved([['sorting_tong',0],['ash_felt',1,{age:2}]]);eq([r.reward,r.total],[6,7]);A(s.pool.some(x=>x.type==='copper_burr'));eq(r.log.filter(e=>e.facts.cause==='self_mature').length,0)});
test('transform/sieve-preserves-uid-permanent-clears-counter',()=>{const {s,r}=resolved([['sieve_drum',0],['spent_gasket',1,{},7]]);eq([s.pool[1].uid,s.pool[1].type,s.pool[1].permanent,s.pool[1].epoch],['u2','copper_burr',7,1]);eq(amounts(r),[2,9])});
test('transform/coil-tide-listener-lining-no-reappear',()=>{const {s,r}=resolved([['condense_coil',0],['saline_ampoule',1],['root_ledger',6]],['item_brine_lining']);eq(amounts(r),[1,11,1]);eq(r.total,13);eq(s.pool[1].epoch,1);eq(r.log.map(e=>[e.action,e.source,e.target,e.parent]),[['transform','u1','u2',null],['add','u2','u2',0],['add','item_brine_lining','u2',0]])});
test('consume/deep-still-mist-generates-and-residue',()=>{const {s,r}=resolved([['deep_still',0],['mist_pouch',1]],['item_residue_stamp']);eq(amounts(r),[2,0]);eq([r.reward,r.total,s.nextUid],[6,8,4]);eq(s.pool.map(x=>x.type),['deep_still','saline_ampoule'])});
test('pressure/reserve-consume-amber-owner-reward-release',()=>{const {s,r}=resolved([['reserve_facet',0,{pressure:4}],['amber_frond',1]]);eq(amounts(r),[2,0]);eq([r.reward,r.total],[24,26]);eq(s.pool[0].counters.pressure,0);eq(r.log.filter(x=>x.action==='reward').map(x=>[x.source,x.amount]),[['u2',4],['u1',2],['u1',18]])});
test('pressure/router-real-mechanism-not-warm-pod',()=>{const {s,r}=resolved([['clinker_router',0],['spent_gasket',1],['warm_pod',5],['reserve_facet',19,{pressure:4}]]);eq(amounts(r),[2,0,1,2]);eq([r.reward,r.total],[18,23]);eq(s.pool.find(x=>x.type==='reserve_facet').counters.pressure,0);eq(r.log.filter(e=>e.action==='pressureIncrease').map(e=>e.target),['u4'])});
test('summary/auditor-distinct-consumed-types-rational',()=>{const {r}=resolved([['sorting_tong',0],['ash_felt',1],['sorting_tong',10],['spent_gasket',11],['heat_clerk',6],['furnace_auditor',19]]);eq(amounts(r),[1,0,3,1,0,3]);eq([r.reward,r.total],[12,20]);eq(r.ledger.find(x=>x.uid==='u5').ratio,['3','2'])});
test('summary/auditor-same-type-does-not-trigger',()=>{const {r}=resolved([['sorting_tong',0],['spent_gasket',1],['sorting_tong',10],['spent_gasket',11],['furnace_auditor',19]]);eq(amounts(r),[1,0,1,0,2]);A(!r.log.some(x=>x.action==='multiply'))});
test('summary/nursery-two-transforms-only-plant',()=>{const {s,r}=resolved([['mist_pouch',0,{age:2}],['mist_pouch',1,{age:2}],['root_ledger',6],['nursery_gauge',19]]);eq(amounts(r),[4,4,4,3]);eq(r.total,15);eq(s.pool[2].permanent,2)});
test('growth/root-soft-cap-actual-one-no-second-growth',()=>{const {s,r}=resolved([['mist_pouch',0,{age:2}],['mist_pouch',1,{age:2}],['root_ledger',6,{},29]]);eq(s.pool[2].permanent,30);eq(r.log.filter(x=>x.action==='grow').map(x=>x.amount),[1])});
test('age/calendar-filters-matured-shared-guard-fog-stitcher',()=>{const mods=[{eventId:'event_fog_shift',uid:'u2',stageId:3,remaining:2}];const {s,r}=resolved([['mist_pouch',0,{age:2}],['mist_pouch',1,{age:1}],['fog_stitcher',5],['root_ledger',6]],['item_dew_calendar','item_root_wrap'],mods);eq(amounts(r),[7,3,1,3]);eq(s.pool.slice(0,2).map(x=>[x.type,x.counters.age,x.epoch]),[['dew_lantern',0,1],['dew_lantern',0,1]]);eq(s.events.activeModifiers[0].remaining,2);eq(s.itemState.quotas.item_dew_calendar.spin,1)});
test('age/fog-bound-natural-maturity-does-not-consume',()=>{const {s}=resolved([['mist_pouch',0,{age:2}],['mist_pouch',1,{age:1}]],[],[{eventId:'event_fog_shift',uid:'u1',stageId:3,remaining:2}]);eq(s.events.activeModifiers[0].remaining,2);eq(s.pool[1].counters.age,2)});
test('age/stitcher-first-valid-aged-plant-only',()=>{const {s}=resolved([['fog_stitcher',0],['wick_bed',1],['mist_pouch',5,{age:1}]]);eq(s.pool[2].type,'dew_lantern')});
test('item/apron-first-success-only',()=>{const {s,r}=resolved([['sorting_tong',0],['spent_gasket',1],['sorting_tong',10],['spent_gasket',11]],['item_sorting_apron']);eq(r.reward,15);eq(s.itemState.quotas.item_sorting_apron,{spin:1,stage:1,run:1})});
test('item/offcut-nonjunk-only-next-pool',()=>{const {s,r}=resolved([['sorting_tong',0],['copper_burr',1]],['item_offcut_chute']);eq(s.pool.map(x=>x.type),['sorting_tong','ash_felt']);eq(r.total,7);eq(s.nextUid,4)});
test('item/offcut-junk-does-not-consume-budget',()=>{const {s}=resolved([['sorting_tong',0],['spent_gasket',1]],['item_offcut_chute']);eq(s.itemState.quotas.item_offcut_chute.spin,0);eq(s.nextUid,3)});
test('item/root-wrap-first-plant-only',()=>{const {r}=resolved([['mist_pouch',0,{age:2}],['mist_pouch',1,{age:2}]],['item_root_wrap']);eq(amounts(r),[7,3])});
test('item/frost-stage-quota-two-appearances',()=>{const {s,r}=resolved([['mist_pouch',0],['mist_pouch',1],['brine_strip',19]],['item_frost_glass']);eq(amounts(r),[4,4,1]);eq(s.itemState.quotas.item_frost_glass.stage,2);s.spin++;const board=Array(20).fill(null);s.pool.forEach((x,i)=>board[i]=x);const next=F.sliceResolve(s,board);eq(next.log.filter(x=>x.source==='item_frost_glass').length,0)});
test('item/waste-log-real-nonconsumed-third-stage',()=>{const {s}=resolved([['clinker_router',0],['spent_gasket',1]],['item_waste_log']);eq(s.itemState.quotas.item_waste_log.stage,1);s.pool.push(F.instance(s,'spent_gasket'));s.spin++;let b=Array(20).fill(null);b[0]=s.pool[0];b[1]=s.pool[1];F.sliceResolve(s,b);s.pool.push(F.instance(s,'spent_gasket'));s.spin++;b=Array(20).fill(null);b[0]=s.pool[0];b[1]=s.pool[1];F.sliceResolve(s,b);eq(s.removeTokens,3);A(s.itemState.used.item_waste_log.stage)});
test('item/fraction-gauge-rechecks-no-available-three-crystals',()=>{const {s,r}=resolved([['tide_prism',0],['crystal_index',1],['reserve_facet',2]],['item_fraction_gauge']);eq([r.reward,r.total],[7,20]);eq(s.itemState.quotas.item_fraction_gauge.spin,1);A(!s.fractionGaugeReserved)});
test('item/fraction-two-types-no-reward',()=>{const {s,r}=resolved([['tide_prism',0],['tide_prism',1],['reserve_facet',2]],['item_fraction_gauge']);eq(r.reward,0);eq(s.itemState.quotas.item_fraction_gauge.spin,0)});
test('appearance/crystal-index-distinct-not-count',()=>{const {r}=resolved([['crystal_index',0],['crystal_index',1]]);eq(amounts(r),[1,1])});
// Snapshot index +6 persists through conversion, then tide +3: 4+6+3=13.
test('transform/pearl-only-nonproduct-and-no-goal-equals',()=>{const {r}=resolved([['pearl_separator',0],['crystal_index',1],['tide_prism',5]]);eq(amounts(r),[2,13,4]);eq(r.log.filter(x=>x.action==='transform').map(x=>x.target),['u2'])});
test('draw/12-random-slots-19-consumed-no-other-stream',()=>{const s=fresh(),before=F.clone(s.rng);const b=F.sliceDraw(s);eq(b.filter(Boolean).length,12);eq(s.rng.draw.consumed,19);A(b.slice(12).some(Boolean));for(const k of F.STREAMS.filter(k=>k!=='draw'))eq(s.rng[k],before[k])});
test('draw/weighted-21-no-replacement-20-plus19-draws',()=>{const s=fresh();s.pool=Array.from({length:21},()=>F.instance(s,'spent_gasket'));s.items=['item_clean_mesh'];const b=F.sliceDraw(s);eq(new Set(b.filter(Boolean).map(x=>x.uid)).size,20);eq(s.rng.draw.consumed,39)});
test('draw/reservation-occupies-original-and-consumed',()=>{const s=fresh();s.reservations=[{uid:'u1',pos:19,epoch:0,source:'u2',expiresSpin:1}];const b=F.sliceDraw(s);eq(b[19].uid,'u1');eq(s.reservations,[]);eq(s.rng.draw.consumed,18)});
test('offer/natural-common-consumes-stage-once-refresh-not-natural',()=>{const s=fresh();F.sliceOffer(s,'symbol');eq(s.offer.guarantees.applied,'stage-common');eq(F.sliceSymbols[s.offer.choices[0]].rarity,'common');eq(s.rng.symbolOffer.consumed,5);const wid=s.offer.windowId;F.sliceOffer(s,'symbol',false);eq(s.offer.guarantees.applied,null);eq(s.offer.windowId,wid);eq(s.rng.symbolOffer.consumed,11);eq(s.offer.choices.length,new Set(s.offer.choices).size)});
test('offer/event-crystal-before-product-common-suppressed',()=>{const s=fresh(),g=s.offer.guarantees;g.eventCrystalPending=g.itemProductPending=true;F.sliceOffer(s,'symbol');eq(g.applied,'event-crystal');A(F.sliceSymbols[s.offer.choices[0]].tags.includes('crystal'));A(!g.eventCrystalPending&&g.itemProductPending&&g.stageCommonHandled);F.sliceOffer(s,'symbol');eq(g.applied,'item-product');eq(s.offer.choices[0],'copper_burr');A(!g.itemProductPending)});
const cmd=(s,op,extra={})=>F.sliceCommand(s,Object.assign({revision:s.revision,op,windowId:s.offer.windowId},extra));
const spin=s=>{const r=cmd(s,'spin');A(r.ok,r.error);return r.state};
test('transaction/spin-pending-reload-no-cash-no-rng-replay',()=>{const s=fresh(),n=spin(s);eq(n.cash,0);eq(n.pendingSettlement,n.last.total);eq(F.decode(F.encode(n)),n);eq(s.spin,0);eq(n.revision,1);eq(n.rng.draw.consumed,19)});
test('transaction/refresh-0-to3-revision-doubleclick-reject',()=>{let s=spin(fresh());s.rerollTokens=9;for(let i=1;i<=3;i++){const r=cmd(s,'reroll');A(r.ok,r.error);s=r.state;eq(s.offer.choiceRefreshesUsed,i);eq(F.decode(F.encode(s)),s)}const bytes=J(s);A(!cmd(s,'reroll').ok);eq(J(s),bytes);A(!F.sliceCommand(s,{revision:0,op:'skip',windowId:s.offer.windowId}).ok)});
test('transaction/full200-offer-delete-choose201-reject-no-uid-loss',()=>{let s=fresh();s.pool=Array.from({length:200},()=>F.instance(s,'wick_bed'));s=spin(s);eq(s.offer.choices.length,3);const bytes=J(s),uid=s.nextUid;A(!cmd(s,'choose',{id:s.offer.choices[0]}).ok);eq(J(s),bytes);eq(s.nextUid,uid);s=cmd(s,'remove',{uid:s.pool[0].uid}).state;const r=cmd(s,'choose',{id:s.offer.choices[0]});A(r.ok,r.error);eq(r.state.pool.length,200)});
function payment(stage,delta){let s=spin(fresh());s.stageId=stage;s.stageSpin=F.NORMAL_SPINS[stage-1];s.spin=F.NORMAL_SPINS.slice(0,stage).reduce((a,b)=>a+b,0);s.spinsRemaining=0;s.itemState.stageId=stage;s.itemState.spin=s.spin;s.last.spin=s.spin;s.basePayment=s.payment=F.SLICE_PAYMENTS[stage-1];s.cash=s.payment+delta-s.pendingSettlement;return s}
for(const stage of [1,10])for(const delta of [-1,0,1])test('payment/stage'+stage+'/delta'+delta,()=>{const s=payment(stage,delta),r=cmd(s,'skip');A(r.ok,r.error);eq(r.state.phase,delta<0?'LOST':stage===10?'WON':'ITEM_CHOICE');if(delta>=0)eq(r.state.cash,delta);eq(r.state.pendingSettlement,null);eq(r.state.stageId,stage);if(stage===10)eq(r.state.rng.itemOffer.consumed,0)});
test('payment/item-choice-only-two-remaining-weighted-not-static',()=>{const s=payment(9,0);s.items=Object.keys(F.sliceItems).slice(0,8);for(const id of s.items){s.itemState.quotas[id]={spin:0,stage:0,run:0};s.itemState.used[id]={spin:false,stage:false}}const r=cmd(s,'skip');A(r.ok,r.error);eq(r.state.offer.choices.length,2);A(r.state.offer.choices.every(x=>!s.items.includes(x)))});
test('setup/skip-item-awards-next-stage-tokens-once',()=>{const s=cmd(payment(1,0),'skip').state,r=cmd(s,'skipItem');A(r.ok,r.error);eq([r.state.stageId,r.state.spinsRemaining,r.state.rerollTokens,r.state.removeTokens],[2,6,3,2]);const duplicate=F.sliceCommand(r.state,{revision:s.revision,op:'skipItem',windowId:s.offer.windowId});A(!duplicate.ok)});
function eventState(id){const s=payment(2,20);s.phase='EVENT_CHOICE';s.stageId=3;s.stageSpin=0;s.spin=12;s.spinsRemaining=7;s.basePayment=s.payment=137;s.itemState.stageId=3;s.itemState.spin=12;s.last.spin=12;s.pendingSettlement=null;s.offer.kind=null;s.offer.choices=[];s.offer.guarantees.applied=null;s.events={seenIds:[id],count:1,cooldownPayments:1,activeModifiers:[],choice:{id,options:['A','B'],targetUids:F.sliceEventTargets(s,id),cost:F.sliceEvents[id].cost,stageId:3}};F.validateState(s);return s}
for(const id of Object.keys(F.sliceEvents)){
test('event/'+id+'/reject-reload-no-rng',()=>{const s=eventState(id),before=F.clone(s.rng);eq(F.decode(F.encode(s)),s);const r=cmd(s,'event',{id,option:'B'});A(r.ok,r.error);eq(r.state.phase,'READY');eq(r.state.rng,before);eq(r.state.events.count,1);eq(r.state.events.cooldownPayments,1)});
test('event/'+id+'/invalid-target-atomic',()=>{const s=eventState(id),before=J(s);A(!cmd(s,'event',{id,option:'A',uid:'u999'}).ok);eq(J(s),before)});
test('event/'+id+'/confirm-effect-no-runtime-listener',()=>{const s=eventState(id),c=s.events.choice,uid=c.targetUids[0],before=F.clone(s),r=cmd(s,'event',{id,option:'A',uid});A(r.ok,r.error);eq(r.state.rng,before.rng);eq(r.state.last,before.last);eq(r.state.phase,'READY');if(id==='event_fog_shift'){eq(r.state.cash,before.cash-4);eq(r.state.events.activeModifiers[0],{eventId:id,uid,stageId:3,remaining:2})}if(id==='event_copper_queue'){eq(r.state.pool.length,before.pool.length+1);eq(r.state.nextUid,before.nextUid+1);eq(r.state.pool.find(x=>x.uid===uid).type,'copper_burr')}if(id==='event_brine_inspection'){eq(r.state.pool.length,before.pool.length-1);A(r.state.offer.guarantees.eventCrystalPending)}});
}
test('event/fog-cost-insufficient-no-commit',()=>{const s=eventState('event_fog_shift');s.cash=3;const b=J(s);A(!cmd(s,'event',{id:s.events.choice.id,option:'A',uid:s.events.choice.targetUids[0]}).ok);eq(J(s),b)});
test('event/copper-capacity-200-rejected',()=>{const s=eventState('event_copper_queue');while(s.pool.length<200)s.pool.push(F.instance(s,'spent_gasket'));const b=J(s);A(!cmd(s,'event',{id:s.events.choice.id,option:'A',uid:s.events.choice.targetUids[0]}).ok);eq(J(s),b)});
test('save/import-preview-and-write-fault-no-publication',()=>{const s=spin(fresh()),data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};A(F.store(storage,s).ok);const bytes=data.get(F.SAVE_KEY),n=F.clone(s);n.cash=10;let r=F.commitImport(storage,F.encode(n),()=>{throw Error('preview fault')},'slice-abd-v1');A(!r.ok&&!r.state);eq(data.get(F.SAVE_KEY),bytes);storage.setItem=()=>{throw Error('storage fault')};r=F.commitImport(storage,F.encode(n),()=>{},'slice-abd-v1');A(!r.ok&&!r.state);eq(data.get(F.SAVE_KEY),bytes)});
test('save/pending-extended-log-roundtrip',()=>{const s=spin(fresh());eq(F.decode(F.encode(s)),s);A(s.last.log.every(x=>Object.hasOwn(x,'facts')))});
return cases;
};
})(typeof window!=='undefined'?window:globalThis);
