(function(root){'use strict';const baseline=root.runGdd1F2Tests;root.runGdd1F2Tests=function(){const cases=baseline(),F=root.GDD1,A=(x,m='assert')=>{if(!x)throw Error(m)},eq=(a,b)=>A(JSON.stringify(a)===JSON.stringify(b),'different'),test=(name,fn)=>{try{fn();cases.push({name:'f2-extra/'+name,ok:true})}catch(e){cases.push({name:'f2-extra/'+name,ok:false,error:e.message})}},cmd=(s,op,extra={})=>{const r=F.sliceCommand(s,Object.assign({revision:s.revision,windowId:s.offer.windowId,op},extra));A(r.ok,r.error);return r.state};
function strong(seed){const s=F.sliceNewRun(seed);s.pool=Array.from({length:20},()=>{const x=F.instance(s,'wick_bed');x.permanent=30;return x});return s}
for(let seed=0;seed<8;seed++)test('70-spin-ten-payments-reload-every-command-'+seed,()=>{let s=strong('complete'+seed),spins=0,items=0;while(!['WON','LOST'].includes(s.phase)){const old=s;if(s.phase==='READY'){s=cmd(s,'spin');spins++}else if(s.phase==='SYMBOL_CHOICE')s=cmd(s,'skip');else if(s.phase==='ITEM_CHOICE'){s=cmd(s,'item',{id:s.offer.choices[0]});items++}else s=cmd(s,'event',{id:s.events.choice.id,option:'B'});A(s.revision===old.revision+1);eq(F.decode(F.encode(s)),s)}eq([s.phase,spins,items,s.spin,s.stageId],['WON',70,9,70,10]);eq(s.rerollTokens,9);eq(s.removeTokens,9)});
for(let seed=0;seed<20;seed++)test('seed-replay-all-five-streams-'+seed,()=>{let a=F.sliceNewRun('replay'+seed),b=F.sliceNewRun('replay'+seed);for(let i=0;i<30&&!['WON','LOST'].includes(a.phase);i++){const extra=a.phase==='EVENT_CHOICE'?{id:a.events.choice.id,option:'B'}:a.phase==='SYMBOL_CHOICE'?{id:a.offer.choices[0]}:a.phase==='ITEM_CHOICE'?{id:a.offer.choices[0]}:{};const op={READY:'spin',SYMBOL_CHOICE:'choose',ITEM_CHOICE:'item',EVENT_CHOICE:'event'}[a.phase];a=cmd(a,op,extra);b=cmd(F.decode(F.encode(b)),op,extra);eq(a,b)}});
test('fraction-reservation-not-stable-state-field',()=>{let s=F.sliceNewRun('fraction');s.pool=['tide_prism','crystal_index','reserve_facet'].map(t=>F.instance(s,t));s.items=['item_fraction_gauge'];s.itemState.quotas.item_fraction_gauge={spin:0,stage:0,run:0};s.itemState.used.item_fraction_gauge={spin:false,stage:false};s.stageId=2;s.spin=6;s.stageSpin=0;s.spinsRemaining=6;s.payment=s.basePayment=82;s.itemState.stageId=2;s.itemState.spin=6;s.last={spin:6,total:0,reward:0,board:Array(20).fill(null),ledger:[],log:[]};s=cmd(s,'spin');eq(s.last.reward,7);eq(s.fractionGaugeReserved,false);F.validateState(s)});
function hand(types,items=[]){const s=F.sliceNewRun('extra');s.pool=types.map(t=>F.instance(s,t));s.items=items;for(const id of items){s.itemState.quotas[id]={spin:0,stage:0,run:0};s.itemState.used[id]={spin:false,stage:false}}s.spin=s.stageSpin=1;s.spinsRemaining=5;const board=Array(20).fill(null);s.pool.forEach((x,i)=>board[i]=x);return{s,board}}
test('multiplier-three-sources-per-effect-target-cap2-single-floor',()=>{const {s,board}=hand(['mist_pouch','mist_pouch','nursery_gauge','nursery_gauge','nursery_gauge']);s.pool[0].counters.age=s.pool[1].counters.age=2;const r=F.sliceResolve(s,board);eq(r.ledger[0].ratio,['9','4']);eq(r.ledger[0].amount,6);eq(r.log.filter(x=>x.action==='limitSkipped'&&x.facts.skipReason==='multiplier-budget').length,5)});
test('multiplier-negative-rational-floor-with-generic-data',()=>{const e=F.sliceSymbols.nursery_gauge.effects[0],old=e.selector.tag;delete e.selector.tag;try{const {s,board}=hand(['mist_pouch','mist_pouch','nursery_gauge','spent_gasket']);s.pool[0].counters.age=s.pool[1].counters.age=2;const r=F.sliceResolve(s,board);eq(r.ledger[3].amount,-2)}finally{e.selector.tag=old}});
test('generation-global2-third-ash-no-uid-consumption',()=>{const {s}=hand(['sorting_tong','ash_felt','sorting_tong','ash_felt','sorting_tong','ash_felt']);const b=Array(20).fill(null),positions=[0,1,10,11,18,19];s.pool.forEach((x,i)=>b[positions[i]]=x);const uid=s.nextUid,r=F.sliceResolve(s,b);eq(r.reward,18);eq(s.nextUid,uid+2);eq(r.log.filter(x=>x.action==='spawn').length,2);A(r.log.some(x=>x.action==='limitSkipped'&&x.facts.skipReason==='generation-budget'))});
test('generation-full200-after-death-first-spawn-second-cap-skipped',()=>{const {s,board}=hand(['sorting_tong','ash_felt'],['item_offcut_chute']);while(s.pool.length<200)s.pool.push(F.instance(s,'wick_bed'));const uid=s.nextUid,r=F.sliceResolve(s,board);eq(s.pool.length,200);eq(s.nextUid,uid+1);eq(r.reward,6);A(r.log.some(x=>x.action==='limitSkipped'&&x.facts.skipReason==='pool-cap'));eq(s.itemState.quotas.item_offcut_chute.spin,0)});
test('pressure-first-full-target-searches-next-valid-no-quota-waste',()=>{const {s,board}=hand(['clinker_router','spent_gasket','reserve_facet','reserve_facet']);s.pool[2].counters.pressure=6;const r=F.sliceResolve(s,board);eq(r.log.filter(x=>x.action==='pressureIncrease').map(x=>x.target),[s.pool.find(x=>x.uid===board[3].uid).uid]);eq(s.pool.find(x=>x.uid===board[3].uid).counters.pressure,2)});
test('dead-source-listener-not-permitted',()=>{const {s}=hand(['sorting_tong','heat_clerk','sorting_tong','ash_felt']);const board=Array(20).fill(null);[0,1,10,11].forEach((p,i)=>board[p]=s.pool[i]);const def=F.sliceSymbols.heat_clerk,old=def.tags;def.tags=['scrap'];try{const r=F.sliceResolve(s,board);eq(r.ledger[1].amount,0);A(!r.log.some(x=>x.action==='grow'&&x.source==='u14'))}finally{def.tags=old}});
test('invalid-command-resolver-fault-rng-and-state-atomic',()=>{const s=F.sliceNewRun('fault'),before=JSON.stringify(s),resolve=F.sliceResolve;F.sliceResolve=()=>{throw Error('injected resolve')};try{A(!F.sliceCommand(s,{op:'spin',revision:s.revision}).ok);eq(JSON.stringify(s),before)}finally{F.sliceResolve=resolve}});
let triggered=0,missed=0,cooldownChecked=0;
for(let seed=0;seed<30;seed++)test('event-eligibility-40percent-cooldown-'+seed,()=>{let s=strong('event'+seed);s.pool.push(F.instance(s,'spent_gasket'),F.instance(s,'saline_ampoule'));s.cash=100000;let previousCount=0,cooldown=false;while(s.stageId<5){if(s.phase==='READY')s=cmd(s,'spin');else if(s.phase==='SYMBOL_CHOICE')s=cmd(s,'skip');else if(s.phase==='EVENT_CHOICE')s=cmd(s,'event',{id:s.events.choice.id,option:'B'});else{const old=F.clone(s);s=cmd(s,'skipItem');if(old.stageId===1)eq(s.rng.event.consumed,0);if(old.stageId>=2){if(cooldown){eq(s.events.count,previousCount);eq(s.rng.event,old.rng.event);cooldownChecked++}else{const n=s.rng.event.consumed-old.rng.event.consumed;A(n===1||n===2);if(n===2){triggered++;A(s.events.count===old.events.count+1);cooldown=true}else{missed++;cooldown=false}}if(old.events.cooldownPayments)cooldown=false;previousCount=s.events.count}}}A(s.events.count<=3);eq(s.events.seenIds.length,new Set(s.events.seenIds).size)});
test('event-coverage-both-roll-outcomes-and-cooldown',()=>A(triggered>0&&missed>0&&cooldownChecked>0));
test('contributions-item-add-own-tide-and-consumer-independent',()=>{const {s,board}=hand(['condense_coil','saline_ampoule'],['item_brine_lining']);const r=F.sliceResolve(s,board);eq(r.ledger[1].contributions,[{source:'u14',amount:7},{source:'item_brine_lining',amount:4}]);eq(r.ledger.flatMap(x=>x.contributions).reduce((a,b)=>a+b.amount,0)+r.log.filter(x=>x.action==='reward').reduce((a,b)=>a+b.amount,0),r.total)});
test('contributions-multiplier-margins-and-final-rounding',()=>{const {s,board}=hand(['mist_pouch','mist_pouch','nursery_gauge','nursery_gauge']);s.pool[0].counters.age=s.pool[1].counters.age=2;const r=F.sliceResolve(s,board);eq(r.ledger[0].contributions,[{source:'u13',amount:3},{source:'u15',amount:1},{source:'u16',amount:2}]);eq(r.ledger[0].amount,6)});
test('contributions-death-zero-normal-reward-own-uid',()=>{const {s,board}=hand(['reserve_facet','amber_frond']);const r=F.sliceResolve(s,board);eq(r.ledger[1].contributions,[]);eq(r.log.filter(x=>x.action==='reward').map(x=>[x.source,x.amount]),[['u14',4],['u13',2]])});
test('schema-rejects-corrupt-contribution-without-weakened-old-ledger',()=>{let s=cmd(F.sliceNewRun('contribution-validation'),'spin');s.last.ledger[0].contributions[0].amount++;let rejected=false;try{F.validateState(s)}catch(e){rejected=true}A(rejected)});
return cases};})(typeof window!=='undefined'?window:globalThis);
