'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),{spawn}=require('child_process'),assert=require('assert');const root=path.resolve(__dirname,'../..'),edge='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',profile=fs.mkdtempSync(path.join(os.tmpdir(),'f4-real-ui-')),outname=process.argv[2]||'f4-ui-cdp-v1';let browser,ws,server;const pending=new Map();let seq=0;
const save=(name,data)=>fs.writeFileSync(path.join(__dirname,outname+'-'+name),data,{flag:'wx'});
async function call(method,params={},sessionId){const id=++seq;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method))},20000);pending.set(id,{resolve:v=>{clearTimeout(timeout);resolve(v)},reject:e=>{clearTimeout(timeout);reject(e)}});ws.send(JSON.stringify({id,method,params,...sessionId?{sessionId}:{}}))});}
(async()=>{server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=spawn(edge,['--headless','--disable-gpu','--no-first-run','--allow-file-access-from-files','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
const deadline=Date.now()+20000;let port;while(Date.now()<deadline){try{port=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n');break}catch{}await new Promise(r=>setTimeout(r,100))}assert(port,'Edge did not publish CDP endpoint');ws=new WebSocket('ws://127.0.0.1:'+port[0]+port[1]);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});ws.addEventListener('message',e=>{const data=JSON.parse(e.data);if(data.id&&pending.has(data.id)){const p=pending.get(data.id);pending.delete(data.id);data.error?p.reject(Error(JSON.stringify(data.error))):p.resolve(data.result)}});
const results=[];for(const [route,url]of [['file','file:///'+root.replace(/\\/g,'/')+'/gdd1.html'],['http','http://127.0.0.1:'+server.address().port+'/gdd1.html']]){const {targetId}=await call('Target.createTarget',{url:'about:blank'}),{sessionId}=await call('Target.attachToTarget',{targetId,flatten:true});await call('Page.enable',{},sessionId);await call('Runtime.enable',{},sessionId);await call('Page.addScriptToEvaluateOnNewDocument',{source:"window.confirm=()=>true;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(window.__faultStorage)throw Error('F4 injected storage fault');return original.call(this,k,v)};"},sessionId);
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true},sessionId);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};const ready=()=>evaluate("new Promise((resolve,reject)=>{const start=Date.now(),timer=setInterval(()=>{if(window.GDD1UI&&document.getElementById('stats').children.length){clearInterval(timer);resolve(true)}else if(Date.now()-start>8000){clearInterval(timer);reject(Error('real UI failed to initialize: '+document.getElementById('notice')?.textContent))}},25)})");
await call('Page.navigate',{url},sessionId);await ready();assert(await evaluate("document.getElementById('new-full')!==null"));await evaluate("document.getElementById('save').click();document.getElementById('new-full').click();document.getElementById('advance-accepted').checked=true;document.getElementById('advance-accepted').dispatchEvent(new Event('change'));true");let s=await evaluate('GDD1UI.getState()');assert.strictEqual(s.profile,'full-v1');assert.strictEqual(s.pool.length,12);assert.strictEqual(s.settings.advanceAccepted,true);assert(await evaluate('!!localStorage.getItem(GDD1.SAVE_KEY)&&!!localStorage.getItem(GDD1.FULL_SAVE_KEY)'));const sliceBytes=await evaluate('localStorage.getItem(GDD1.SAVE_KEY)');await evaluate("document.querySelector('[data-op=spin]').click();document.querySelector('[data-op=skip]').click();document.getElementById('save').click();true");s=await evaluate('GDD1UI.getState()');assert.strictEqual(s.phase,'READY');assert.strictEqual(s.spin,1);assert.strictEqual(await evaluate('localStorage.getItem(GDD1.SAVE_KEY)'),sliceBytes);await call('Page.reload',{},sessionId);await ready();assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),s);
// Exercise real delegated double-click suppression, stale DOM, and refresh cap.
const legacyBefore=await evaluate('GDD1.LEGACY_KEYS.map(k=>localStorage.getItem(k))');
await evaluate("new Promise(resolve=>{const fixture=GDD1.clone(GDD1UI.getState());fixture.rerollTokens=9;const input=document.getElementById('import'),d=new DataTransfer();d.items.add(new File([GDD1.encode(fixture)],'valid-full.json',{type:'application/json'}));input.files=d.files;input.dispatchEvent(new Event('change'));setTimeout(resolve,150)})");
assert.strictEqual((await evaluate('GDD1UI.getState()')).rerollTokens,9);assert.strictEqual(await evaluate('localStorage.getItem(GDD1.SAVE_KEY)'),sliceBytes);
await evaluate("document.querySelector('[data-op=spin]').click();window.__oldRefresh=document.querySelector('[data-op=reroll]');window.__oldRefresh.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));true");
let refreshed=await evaluate('GDD1UI.getState()');assert.strictEqual(refreshed.offer.choiceRefreshesUsed,1);assert.strictEqual(refreshed.rerollTokens,8);
await evaluate("document.querySelector('[data-op=reroll]').dispatchEvent(new MouseEvent('click',{bubbles:true,detail:2}));window.__oldRefresh.click();true");assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),refreshed);
for(let count=2;count<=3;count++){await evaluate("document.querySelector('[data-op=reroll]').dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));true");refreshed=await evaluate('GDD1UI.getState()');assert.strictEqual(refreshed.offer.choiceRefreshesUsed,count);assert.strictEqual(refreshed.rerollTokens,9-count);}
assert(await evaluate("document.querySelector('[data-op=reroll]').disabled"));await evaluate("document.querySelector('[data-op=reroll]').click();true");assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),refreshed);
await evaluate("document.querySelector('[data-op=skip]').click();true");s=await evaluate('GDD1UI.getState()');await call('Page.reload',{},sessionId);await ready();assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),s);assert.strictEqual(await evaluate('localStorage.getItem(GDD1.SAVE_KEY)'),sliceBytes);assert.deepStrictEqual(await evaluate('GDD1.LEGACY_KEYS.map(k=>localStorage.getItem(k))'),legacyBefore);
results.push({route,case:'valid-full-import-exact-reload-real-double-click-detail2-stale-detached-button-refresh-cap3-other-legacy-keys',ok:true});
// Schema-valid funded states generated through commands, then real UI boundaries.
await evaluate("window.__f4Fixture=(kind)=>{for(let seed=0;seed<12;seed++){let t=GDD1.fullNewRun('UI-BOUNDARY-'+seed);t.cash=1000000;for(let n=0;n<300;n++){if(kind==='item'&&t.phase==='ITEM_CHOICE'||kind==='event'&&t.phase==='EVENT_CHOICE'||kind==='final'&&t.phase==='SYMBOL_CHOICE'&&t.stageId===10&&t.spinsRemaining===0)return t;if(['WON','LOST'].includes(t.phase))break;const cmd=t.phase==='READY'?{op:'spin'}:t.phase==='SYMBOL_CHOICE'?{op:'skip',windowId:t.offer.windowId}:t.phase==='ITEM_CHOICE'?{op:'skipItem',windowId:t.offer.windowId}:{op:'event',id:t.events.choice.id,option:'B'};const r=GDD1.fullCommand(t,{...cmd,revision:t.revision});if(!r.ok)throw Error(r.error);t=r.state;}}throw Error('no UI fixture '+kind);};window.__f4Import=async(t)=>{const input=document.getElementById('import'),d=new DataTransfer();d.items.add(new File([GDD1.encode(t)],'boundary.json',{type:'application/json'}));input.files=d.files;input.dispatchEvent(new Event('change'));await new Promise(r=>setTimeout(r,150));};true");
const readyState=s;
for(const kind of ['item','event','final']){
 await evaluate("__f4Import(__f4Fixture('"+kind+"'))");const boundary=await evaluate('GDD1UI.getState()');let command;
 if(kind==='item')command={op:'item',id:boundary.offer.choices[0],windowId:boundary.offer.windowId};
 else if(kind==='event')command={op:'event',id:boundary.events.choice.id,option:'A',uid:boundary.events.choice.targetUids[0]||null};
 else command={op:'skip',windowId:boundary.offer.windowId};
 const expected=await evaluate('GDD1.fullCommand(GDD1UI.getState(),'+JSON.stringify({...command,revision:boundary.revision})+').state');
 if(kind==='event')await evaluate("document.getElementById('event-target').value="+JSON.stringify(command.uid||'')+";document.querySelector('[data-op=event][data-option=A]').click();true");
 else await evaluate("document.querySelector('[data-op="+command.op+"]').click();true");
 assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),expected);assert.strictEqual(await evaluate('localStorage.getItem(GDD1.SAVE_KEY)'),sliceBytes);assert.deepStrictEqual(await evaluate('GDD1.LEGACY_KEYS.map(k=>localStorage.getItem(k))'),legacyBefore);
 if(kind==='event'){await evaluate('__f4Import('+JSON.stringify(boundary)+')');const declined=await evaluate('GDD1.fullCommand(GDD1UI.getState(),'+JSON.stringify({op:'event',id:boundary.events.choice.id,option:'B',revision:boundary.revision})+').state');await evaluate("document.querySelector('[data-op=event][data-option=B]').click();true");assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),declined);}
 if(kind==='final'){assert.strictEqual(expected.phase,'WON');assert.strictEqual(expected.spin,70);assert.strictEqual(expected.rerollTokens,boundary.rerollTokens);assert.strictEqual(expected.removeTokens,boundary.removeTokens);await call('Page.reload',{},sessionId);await ready();assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),expected);await evaluate("window.__f4Import=async(t)=>{const input=document.getElementById('import'),d=new DataTransfer();d.items.add(new File([GDD1.encode(t)],'boundary.json',{type:'application/json'}));input.files=d.files;input.dispatchEvent(new Event('change'));await new Promise(r=>setTimeout(r,150));};true");}
 results.push({route,case:'real-ui-funded-'+kind+'-transaction-exact-engine-parity-other-keys-unchanged',ok:true});
}
await evaluate('__f4Import('+JSON.stringify(readyState)+')');await evaluate("document.querySelector('[data-op=spin]').click();true");const pendingBefore=await evaluate('GDD1UI.getState()');const removeCommand={op:'remove',uid:pendingBefore.pool[0].uid,confirmEmpty:true,revision:pendingBefore.revision};const removed=await evaluate('GDD1.fullCommand(GDD1UI.getState(),'+JSON.stringify(removeCommand)+').state');await evaluate("document.querySelector('[data-op=remove]').click();true");assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),removed);assert.strictEqual(removed.pendingSettlement,pendingBefore.pendingSettlement);results.push({route,case:'real-ui-pending-delete-retains-current-ledger-and-settlement',ok:true});await evaluate('__f4Import('+JSON.stringify(readyState)+')');s=await evaluate('GDD1UI.getState()');
for(const [width,height]of [[1280,720],[1600,900],[1920,1080]]){await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false},sessionId);const layout=await evaluate("({viewport:innerWidth,scroll:document.documentElement.scrollWidth,cells:document.querySelectorAll('#board .cell').length,board:document.getElementById('board').getBoundingClientRect().toJSON()})");assert.strictEqual(layout.cells,20);assert(layout.scroll<=layout.viewport,'horizontal overflow');const shot=await call('Page.captureScreenshot',{format:'png'},sessionId);save(route+'-'+width+'x'+height+'.png',Buffer.from(shot.data,'base64'));results.push({route,case:'real-ui-layout',width,height,layout,ok:true});}
const errorInput=await evaluate('GDD1UI.getState()'),errorStorage=await evaluate('localStorage.getItem(GDD1.FULL_SAVE_KEY)');await evaluate("window.__wickEffects=GDD1.fullSymbols.wick_bed.effects;GDD1.fullSymbols.wick_bed.effects=Array.from({length:5001},(_,i)=>({key:'ui-action-bound:'+i,phase:'appearance',op:'add',selector:{scope:'self'},amount:1,limit:1}));document.querySelector('[data-op=spin]').click();GDD1.fullSymbols.wick_bed.effects=window.__wickEffects;true");assert.deepStrictEqual(await evaluate('GDD1UI.getState()'),errorInput);assert.strictEqual(await evaluate('localStorage.getItem(GDD1.FULL_SAVE_KEY)'),errorStorage);assert.strictEqual(await evaluate('localStorage.getItem(GDD1.SAVE_KEY)'),sliceBytes);assert.deepStrictEqual(await evaluate('GDD1.LEGACY_KEYS.map(k=>localStorage.getItem(k))'),legacyBefore);const errorReport=await evaluate('GDD1UI.getErrorReport()');assert(errorReport.error.includes('Action safety bound'));assert.deepStrictEqual(errorReport.input,errorInput);assert.strictEqual(errorReport.command.op,'spin');assert(await evaluate("!document.getElementById('export-error').disabled"));results.push({route,case:'real-ui-action5000-failure-preserves-seed-state-RNG-storage-and-enables-exportable-error-input',ok:true});
const saved=await evaluate('localStorage.getItem(GDD1.FULL_SAVE_KEY)');await evaluate("window.__faultStorage=true;document.querySelector('[data-op=spin]').click();true");const faultState=await evaluate('GDD1UI.getState()');assert.strictEqual(faultState.phase,'SYMBOL_CHOICE');assert.strictEqual(await evaluate('localStorage.getItem(GDD1.FULL_SAVE_KEY)'),saved);assert((await evaluate("document.getElementById('notice').textContent")).includes('Session-only'));await evaluate("window.__faultStorage=false;true");const prior=await evaluate('JSON.stringify(GDD1UI.getState())');await evaluate("new Promise(resolve=>{const input=document.getElementById('import'),d=new DataTransfer();d.items.add(new File(['{\\\"schema\\\":999}'],'invalid.json',{type:'application/json'}));input.files=d.files;input.dispatchEvent(new Event('change'));setTimeout(resolve,100)})");assert.strictEqual(await evaluate('JSON.stringify(GDD1UI.getState())'),prior);assert.strictEqual(await evaluate('localStorage.getItem(GDD1.FULL_SAVE_KEY)'),saved);results.push({route,case:'real-buttons-full-entry-setting-spin-skip-save-reload-independent-storage-write-fault-invalid-import',ok:true});await call('Target.closeTarget',{targetId});}
save('results.json',JSON.stringify({scope:'Real gdd1.html Edge UI via CDP; not complete F4 acceptance',results},null,2));console.log('PASS '+results.length+' real Edge UI file/HTTP cases, three resolutions, exact reload, separate saves and fault/import rollback');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(ws&&ws.readyState===1){try{await call('Browser.close')}catch{}ws.close()}if(browser&&!browser.killed)browser.kill();if(server)await new Promise(r=>server.close(r));});
