(function(root){
'use strict';
root.runGdd1Retest=async function(){
 const F=root.GDD1,cases=[];
 const A=(v,m='assertion failed')=>{if(!v)throw Error(m)};
 const J=x=>JSON.stringify(x);
 const eq=(a,b,m='json mismatch')=>A(J(a)===J(b),m);
 const rejects=f=>{let yes=false;try{f()}catch(_){yes=true}A(yes,'expected rejection')};
 const state=(stage=3,sp=0,phase='READY')=>{const s=F.createFoundationState('F1-RETEST-BOUNDARY','full-v1');const base=F.NORMAL_SPINS.slice(0,stage-1).reduce((a,b)=>a+b,0);Object.assign(s,{stageId:stage,stageSpin:sp,spin:base+sp,spinsRemaining:F.NORMAL_SPINS[stage-1]-sp,phase});s.basePayment=s.payment=F.NORMAL_PAYMENTS[stage-1];s.itemState.stageId=stage;s.itemState.spin=s.spin;if(s.spin)s.last={spin:s.spin,total:0,reward:0,board:Array(20).fill(null),ledger:[],log:[]};if(phase==='SYMBOL_CHOICE'){s.pendingSettlement=0;Object.assign(s.offer,{windowId:1,kind:'symbol',choices:['mist_pouch']})}return s};
 const mem=()=>{const data=new Map([['fog-port.save.v1','legacy-bytes'],['fog-port.save.v1.backup','backup-bytes']]),reads=[],writes=[];return{data,reads,writes,getItem(k){reads.push(k);return data.has(k)?data.get(k):null},setItem(k,v){writes.push([k,v]);data.set(k,v)}}};
 const target=(s,type,age=0,epoch=0)=>{s.nextUid=2;s.pool=[{uid:'u1',type,permanent:7,epoch,counters:age===null?{}:{age}}];return s};
 const fog=(s,type='mist_pouch',remaining=2,stage=3,age=1)=>{target(s,type,age);s.events.seenIds=['event_fog_shift'];s.events.count=1;s.events.activeModifiers=[{eventId:'event_fog_shift',uid:'u1',stageId:stage,remaining}];return s};
 const check=(name,fn)=>{try{fn();cases.push({name:'retest/'+name,ok:true})}catch(e){cases.push({name:'retest/'+name,ok:false,error:e.message})}};
 check('preview/sync-undefined-clone-and-no-storage-read',()=>{const old=state(),next=F.clone(old);next.cash=41;const m=mem();const oldBytes=J(old),before=Array.from(m.data);let seen,previewReads,previewWrites;const r=F.commitImport(m,F.encode(next),n=>{seen=n;n.cash=999;previewReads=m.reads.length;previewWrites=m.writes.length});A(r.ok&&r.state.cash===41&&seen!==r.state&&previewReads===0&&previewWrites===0);A(m.reads.length===1&&m.writes.length===1);eq(old,JSON.parse(oldBytes));});
 for(const [name,preview] of [['promise-resolve',()=>Promise.resolve()],['promise-reject',()=>{const p=Promise.reject(Error('late'));p.catch(()=>{});return p}],['then-getter',()=>Object.defineProperty({},'then',{get(){throw Error('getter touched')}})],['function-thenable',()=>{const f=()=>{};f.then=()=>{throw Error('then touched')};return f}],['value',()=>null]])check('preview/reject-'+name,()=>{const old=state(),next=F.clone(old);next.cash=42;const m=mem();const before=Array.from(m.data);const r=F.commitImport(m,F.encode(next),preview);A(!r.ok&&!Object.hasOwn(r,'state'));eq(m.reads,[]);eq(m.writes,[]);eq(Array.from(m.data),before);eq(old.cash,0)});
 check('preview/sync-throw-no-publication',()=>{const m=mem(),s=state(),before=Array.from(m.data);const r=F.commitImport(m,F.encode(s),()=>{throw Error('render')});A(!r.ok&&!Object.hasOwn(r,'state'));eq(Array.from(m.data),before)});
 for(const age of [0,1,2])check('ash/legal-age-'+age,()=>{const s=target(state(),'ash_felt',age);F.validateState(s);A(F.decode(F.encode(s)).pool[0].counters.age===age)});
 check('ash/reject-age-3-every-entry',()=>{const s=target(state(),'ash_felt',3),raw=J(s);rejects(()=>F.validateState(s));rejects(()=>F.decode(raw));const m=mem();A(!F.store(m,s).ok&&m.reads.length===0&&m.writes.length===0);A(!F.commitImport(m,raw,()=>{}).ok&&m.reads.length===0&&m.writes.length===0)});
 for(const type of ['mist_pouch','dew_lantern'])for(const rem of [1,2])check('fog/legal-'+type+'-r'+rem,()=>{const s=fog(state(5,4),type,rem,3, type==='mist_pouch'?1:0);F.validateState(s)});
 check('fog/reject-nonplant-age-bearing',()=>{for(const type of ['cloudy_negative','brine_strip','ash_felt'])rejects(()=>F.validateState(fog(state(),type,2,3,1)))});
 check('fog/reject-plant-without-age',()=>{rejects(()=>F.validateState(fog(state(),'mist_pouch',2,3,null)))});
 check('fog/cross-stage-preserves-remaining',()=>{const s=fog(state(9,4),'dew_lantern',2,3,0);F.validateState(s);A(s.events.activeModifiers[0].remaining===2)});
 check('fog/same-uid-mist-to-dew',()=>{const s=fog(state(3,1),'mist_pouch',2,3,2);const uid=s.pool[0].uid,perm=s.pool[0].permanent;s.pool[0].type='dew_lantern';s.pool[0].counters={age:0};s.pool[0].epoch++;F.validateState(s);A(s.pool[0].uid===uid&&s.pool[0].permanent===perm&&s.events.activeModifiers[0].remaining===2)});
 check('fog/natural-maturity-does-not-decrement',()=>{const s=fog(state(4,1),'mist_pouch',2,3,2);const b=J(s.events.activeModifiers);F.validateState(s);eq(s.events.activeModifiers,JSON.parse(b))});
 check('fog/age-less-conversion-must-clear',()=>{const s=fog(state(),'dew_lantern',1);s.pool[0].type='amber_frond';s.pool[0].counters={};s.pool[0].epoch++;rejects(()=>F.validateState(s));s.events.activeModifiers=[];F.validateState(s)});
 check('fog/deletion-and-no-rebind',()=>{const s=fog(state(),'mist_pouch',1);s.pool=[];rejects(()=>F.validateState(s));s.pool=[{uid:'u2',type:'mist_pouch',permanent:0,epoch:0,counters:{age:0}}];s.nextUid=3;rejects(()=>F.validateState(s))});
 for(const [id,w] of [['event_silent_bell',3],['event_misprint_window',3],['event_empty_manifest',1]]){for(const sp of [0,1,2,3])check(id+'/boundary-sp'+sp,()=>{const s=state(3,sp,'READY');s.events.seenIds=[id];s.events.count=1;s.events.activeModifiers=[{eventId:id,uid:null,stageId:3,remaining:w-sp}];if(sp<w)F.validateState(s);else rejects(()=>F.validateState(s))});check(id+'/wrong-stage-clear-point',()=>{const s=state(4,0);s.events.seenIds=[id];s.events.count=1;s.events.activeModifiers=[{eventId:id,uid:null,stageId:3,remaining:w}];rejects(()=>F.validateState(s))})}
 check('fixed-window/transaction-clears-before-symbol-choice',()=>{const s=state(3,2,'SYMBOL_CHOICE');s.events.seenIds=['event_silent_bell'];s.events.count=1;s.events.activeModifiers=[{eventId:'event_silent_bell',uid:null,stageId:3,remaining:1}];const r=F.transact(s,s.revision,n=>{n.spin++;n.stageSpin++;n.spinsRemaining--;n.itemState.spin=n.spin;n.last.spin=n.spin;n.events.activeModifiers=[]});A(r.ok,r.error)});
 await Promise.resolve();return{total:cases.length,passed:cases.filter(x=>x.ok).length,cases,scope:'Independent F1 retest; non-F2 schema/save boundary probes'};
};
})(typeof window!=='undefined'?window:globalThis);
